### ISSUE TITLE
I and l are too similar

### ISSUE THREAD

**Issue by alxgnon** [Kiniamaro/short.maro.xyz#2]
when typing urls, I and l are easy to mix up. Consider using a different font or blacklisting certain characters

**Comment by S0yKaf** [comment]
You're welcome to suggest better fonts that won' affect the aesthetic of the site.

**Comment by alxgnon** [comment]
How about monospace in the url input field? [Static example](http://alxgnon.com/short.maro.xyz/)

### CSS

``` css
input#url {
  font-family: Consolas, "Andale Mono WT", "Andale Mono", "Lucida Console", "Lucida Sans Typewriter", "DejaVu Sans Mono", "Bitstream Vera Sans Mono", "Liberation Mono", "Nimbus Mono L", Monaco, "Courier New", Courier, monospace;
}
```
